version: '3'
services:
    office-system:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: office-system
        command: sleep infinity
        restart: always
        ports:
            - '58452:4200' # Angular
            - '58451:8080' # Java
        volumes:
            - ../:/workspace
        env_file: ./environment.env
        depends_on:
            - office-system-db
    office-system-db:
        image: mariadb:10.7.1
        container_name: office-system-db
        restart: always
        env_file: ./environment.env
        volumes:
            - office-system-db-volume:/var/lib/mariadb/
            - ../database/mariadb.cnf:/etc/mysql/mariadb.cnf
            - ../database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - '58450:3306' # MariaDB
volumes:
    office-system-db-volume:
        driver: local
